export const COMENZAR_DESCARGA_PERSONAJES = "COMENZAR_DESCARGA_PERSONAJES";
export const PERSONAJES_CARGADOS = "PERSONAJES_CARGADOS";
export const PERSONAJES_CARGADOS_ERROR = "PERSONAJES_CARGADOS_ERROR";

export const CARGAR_PERSONAJE = "CARGAR_PERSONAJE";
export const PERSONAJE_CARGADO = "PERSONAJE_CARGADO";
export const PERSONAJE_CARGADO_ERROR = "PERSONAJE_CARGADO_ERROR";